"""create shipments table

Revision ID: 2c044db51519
Revises: eb649a8254e9
Create Date: 2023-10-24 09:55:43.242675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c044db51519'
down_revision = 'eb649a8254e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('shipment_date', sa.Date(), nullable=False),
    sa.Column('shipment_status', sa.String(length=20), nullable=False),
    sa.Column('shipment_address', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('shipment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipments')
    # ### end Alembic commands ###
