"""create_laptops_table

Revision ID: e4af226b6c85
Revises: 0e0aea7ffe40
Create Date: 2023-11-02 10:07:00.062048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4af226b6c85'
down_revision = '0e0aea7ffe40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laptops',
    sa.Column('laptop_id', sa.UUID(), nullable=False),
    sa.Column('manufacturer', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=20), nullable=False),
    sa.Column('make_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('laptop_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laptops')
    # ### end Alembic commands ###
